# Jayatilake Benchmark Configuration
# Minimal config for testing gene network behavior only

# Domain configuration - minimal for testing
domain:
  size_x: 100.0
  size_x_unit: "um"
  size_y: 100.0
  size_y_unit: "um"
  nx: 5
  ny: 5
  dimensions: 2

# Time configuration - minimal steps for testing
time:
  dt: 0.1
  end_time: 1.0
  diffusion_step: 10      # Don't update diffusion often
  intracellular_step: 1   # Update gene networks every step
  intercellular_step: 10  # Don't update interactions often

# Diffusion solver configuration
diffusion:
  max_iterations: 1000
  tolerance: 1e-6
  solver_type: "steady_state"

# Minimal substances for gene network inputs
substances:
  Oxygen:
    diffusion_coeff: 1.0e-9
    production_rate: 0.0
    uptake_rate: 0.0
    initial_value: 0.07
    boundary_value: 0.07
    boundary_type: "fixed"
    unit: "mM"

  Glucose:
    diffusion_coeff: 6.70e-11
    production_rate: 0.0
    uptake_rate: 0.0
    initial_value: 5.0
    boundary_value: 5.0
    boundary_type: "fixed"
    unit: "mM"

  Lactate:
    diffusion_coeff: 6.70e-11
    production_rate: 0.0
    uptake_rate: 0.0
    initial_value: 5.0
    boundary_value: 1.0
    boundary_type: "fixed"
    unit: "mM"

# Gene input associations
associations:
  Oxygen: "Oxygen_supply"
  Glucose: "Glucose_supply"
  Lactate: "MCT1_stimulus"

# Gene input thresholds
thresholds:
  Oxygen_supply:
    initial: 0.07
    threshold: 0.02
  Glucose_supply:
    initial: 5.0
    threshold: 1.0
  MCT1_stimulus:
    initial: 5.0
    threshold: 2.0

# Gene network configuration
gene_network:
  # Path to the real Jayatilake experiment .bnd file
  bnd_file: "tests/jayatilake_experiment/jaya_microc.bnd"
  
  nodes:
    # Input nodes with default states
    Oxygen_supply:
      is_input: true
      default_state: true
    Glucose_supply:
      is_input: true
      default_state: true
    MCT1_stimulus:
      is_input: true
      default_state: true
    Proton_level:
      is_input: true
      default_state: false
    FGFR_stimulus:
      is_input: true
      default_state: false
    EGFR_stimulus:
      is_input: true
      default_state: false
    cMET_stimulus:
      is_input: true
      default_state: false

# Gene network propagation steps
gene_network_steps: 1

# Cell behavior parameters
cell_cycle_time: 240
max_cell_age: 500.0

# Metabolic rates (minimal for testing)
metabolic_rates:
  Proliferation:
    oxygen_consumption_rate: 0.0
    glucose_consumption_rate: 0.0
    lactate_production_rate: 0.0
  Growth_Arrest:
    oxygen_consumption_rate: 0.0
    glucose_consumption_rate: 0.0
    lactate_production_rate: 0.0
  Apoptosis:
    oxygen_consumption_rate: 0.0
    glucose_consumption_rate: 0.0
    lactate_production_rate: 0.0
  Necrosis:
    oxygen_consumption_rate: 0.0
    glucose_consumption_rate: 0.0
    lactate_production_rate: 0.0

output_dir: "benchmarks/gene_network_comparison/results"
plots_dir: "benchmarks/gene_network_comparison/plots"
data_dir: "benchmarks/gene_network_comparison/data"
custom_functions_path: "benchmarks/gene_network_comparison/jayatilake_benchmark_custom_functions.py"
