domain:
  size_x: 800.0
  size_x_unit: "μm"
  size_y: 800.0
  size_y_unit: "μm"
  nx: 40  # CRITICAL: Must give 20μm spacing
  ny: 40
  dimensions: 2
  cell_height: 20.0          # Biological cell height/thickness
  cell_height_unit: "μm"     # Can be changed to make cells thicker/thinner

time:
  dt: 0.01
  end_time: 2.0
  diffusion_step: 5
  intracellular_step: 1
  intercellular_step: 10

# Diffusion solver configuration
diffusion:
  max_iterations: 1000
  tolerance: 1e-6
  solver_type: "steady_state"
  twodimensional_adjustment_coefficient: 1.0  # No adjustment needed (mesh volume already includes thickness)

substances:
  lactate:
    diffusion_coeff: 6.70e-11  # m²/s
    production_rate: 3.0e-15   # mol/s/cell
    uptake_rate: 0.0
    initial_