domain:
  size_x: 800.0
  size_x_unit: "um"
  size_y: 800.0
  size_y_unit: "um"
  nx: 40  # CRITICAL: Must give 20μm spacing
  ny: 40
  dimensions: 2
  cell_height: 20.0          # Biological cell height/thickness
  cell_height_unit: "um"     # Can be changed to make cells thicker/thinner

time:
  dt: 0.01
  end_time: 2.0
  diffusion_step: 5
  intracellular_step: 1
  intercellular_step: 10

# Diffusion solver configuration
diffusion:
  max_iterations: 1000
  tolerance: 1e-6
  solver_type: "steady_state"
  twodimensional_adjustment_coefficient: 1.0  # No adjustment needed (mesh volume already includes thickness)

substances:
  lactate:
    diffusion_coeff: 6.70e-11  # m²/s
    production_rate: 3.0e-15   # mol/s/cell
    uptake_rate: 0.0
    initial_value: 1.0         # mM
    boundary_value: 1.0        # mM
    boundary_type: "fixed"

# Gene network associations
associations:
  lactate: "NA"  # No gene network association for lactate

# Thresholds for gene network inputs
thresholds: {}

# Output configuration
output:
  save_data_interval: 10
  save_plots_interval: 10
  status_print_interval: 5
  save_initial_plots: true
  save_final_plots: true

# Initial state configuration
initial_state:
  mode: "generate"             # "generate", "load_h5", "load_vtk", or "load" (auto-detect)
  file_path: null              # Path to initial state file (.h5 or .vtk)
  save_initial_state: false    # Save initial state after generation

  # VTK loading automatically detects biological cell size from cube geometry
  # and updates domain.cell_height accordingly