# Drug Treatment Study Configuration
# Simulates EGFR inhibitor treatment

domain:
  size_x: 600.0
  size_x_unit: "μm"
  size_y: 600.0  
  size_y_unit: "μm"
  nx: 30
  ny: 30
  dimensions: 2

time:
  dt: 0.02
  end_time: 10.0
  diffusion_step: 5
  intracellular_step: 1
  intercellular_step: 10

# Essential substances + growth factors + drugs
substances:
  # Essential metabolites
  Oxygen:
    diffusion_coeff: 1.0e-9
    production_rate: 0.0
    uptake_rate: 3.0e-17
    initial_value: 0.07
    boundary_value: 0.07
    boundary_type: "fixed"
    
  Glucose:
    diffusion_coeff: 6.70e-11
    production_rate: 0.0
    uptake_rate: 3.0e-15
    initial_value: 5.0
    boundary_value: 5.0
    boundary_type: "fixed"
    
  Lactate:
    diffusion_coeff: 6.70e-11
    production_rate: 3.0e-15
    uptake_rate: 0.0
    initial_value: 1.0
    boundary_value: 1.0
    boundary_type: "fixed"
  
  # Growth factor (high concentration)
  TGFA:
    diffusion_coeff: 5.18e-11
    production_rate: 2.0e-20
    uptake_rate: 2.0e-17
    initial_value: 5.0e-6  # High TGFA
    boundary_value: 5.0e-6
    boundary_type: "fixed"
  
  # EGFR drug (treatment)
  EGFRD:
    diffusion_coeff: 2.2e-10
    production_rate: 0.0
    uptake_rate: 4.0e-17
    initial_value: 10.0e-3  # High drug concentration
    boundary_value: 10.0e-3
    boundary_type: "fixed"

# Drug study associations
associations:
  Oxygen: "Oxygen_supply"
  Glucose: "Glucose_supply"
  Lactate: "MCT1_stimulus"
  TGFA: "EGFR_stimulus"
  EGFRD: "EGFRI"

# Drug study thresholds
thresholds:
  Oxygen_supply:
    initial: 0.07
    threshold: 0.022
  Glucose_supply:
    initial: 5.0
    threshold: 4.0
  MCT1_stimulus:
    initial: 1.0
    threshold: 1.5
  EGFR_stimulus:
    initial: 0.0
    threshold: 1.0e-6  # TGFA activates EGFR
  EGFRI:
    initial: 0.0
    threshold: 5.0e-3  # Drug inhibits EGFR

output_dir: "results/drug_treatment"
plots_dir: "plots/drug_treatment"
data_dir: "data/drug_treatment"
custom_functions_path: "config/custom_functions.py"
