# Simple Oxygen-Glucose Simulation
# Minimal configuration for basic cell metabolism

domain:
  size_x: 400.0
  size_x_unit: "μm"
  size_y: 400.0  
  size_y_unit: "μm"
  nx: 20
  ny: 20
  dimensions: 2

time:
  dt: 0.05
  end_time: 5.0
  diffusion_step: 5
  intracellular_step: 1
  intercellular_step: 10

# Diffusion solver configuration
diffusion:
  max_iterations: 1000
  tolerance: 1e-6
  solver_type: "steady_state"

# Just essential substances
substances:
  Oxygen:
    diffusion_coeff: 1.0e-9
    production_rate: 0.0
    uptake_rate: 3.0e-17
    initial_value: 0.07
    boundary_value: 0.07
    boundary_type: "fixed"
    
  Glucose:
    diffusion_coeff: 6.70e-11
    production_rate: 0.0
    uptake_rate: 3.0e-15
    initial_value: 5.0
    boundary_value: 5.0
    boundary_type: "fixed"
    
  Lactate:
    diffusion_coeff: 6.70e-11
    production_rate: 3.0e-15
    uptake_rate: 0.0
    initial_value: 1.0
    boundary_value: 1.0
    boundary_type: "fixed"

# Simple associations
associations:
  Oxygen: "Oxygen_supply"
  Glucose: "Glucose_supply"

# Simple thresholds
thresholds:
  Oxygen_supply:
    initial: 0.07
    threshold: 0.022
  Glucose_supply:
    initial: 5.0
    threshold: 4.0

output_dir: "results/simple_sim"
plots_dir: "plots/simple_sim"
data_dir: "data/simple_sim"
custom_functions_path: "config/custom_functions.py"
